# Generated by Django 3.2.14 on 2022-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarwashPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=10, unique=True)),
                ('place_name', models.CharField(max_length=50)),
            ],
        ),
    ]
