# Generated by Django 3.2.6 on 2022-08-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_washes', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWPlaces',
            fields=[
                ('carwash_place_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('is_free', models.BooleanField(default=False)),
                ('carwash_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_washes.carwashes')),
                ('place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.places')),
            ],
        ),
    ]
