# Generated by Django 3.2.6 on 2022-08-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CW_places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cwplaces',
            old_name='carwash_id',
            new_name='carwash',
        ),
        migrations.RenameField(
            model_name='cwplaces',
            old_name='carwash_place_id',
            new_name='carwash_place',
        ),
        migrations.RenameField(
            model_name='cwplaces',
            old_name='place_id',
            new_name='place',
        ),
    ]
