# Generated by Django 3.2.14 on 2022-08-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_accounts_managers'),
        ('car_washes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_current_status', models.CharField(max_length=20)),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('execution', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_washes.carwashes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
