# Generated by Django 3.2.14 on 2022-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execution',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
