# Generated by Django 4.1 on 2022-08-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
    ]
