\i data/users.sql
\i data/accounts.sql 
\i data/carwashes.sql 
\i data/pLaces.sql
\i data/carwash_places.sql
\i data/services.sql
\i data/carwash_services.sql
\i data/orders.sql
\i data/order_details.sql
