# Generated by Django 4.1 on 2022-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_wash_name', models.CharField(max_length=50)),
                ('car_wash_address', models.CharField(max_length=255)),
                ('quantity_of_places', models.IntegerField()),
            ],
        ),
    ]
